export const mockStations = [
  {
    id: 1,
    name: "PowerHub Central",
    distance: 2.3,
    chargerType: "CCS2",
    pricePerKwh: 0.35,
    availability: "Available",
    availableChargers: 4,
    totalChargers: 6,
    chargingSpeed: "150 kW",
    address: "123 Main Street, City Center",
  },
  {
    id: 2,
    name: "EcoCharge Station",
    distance: 3.1,
    chargerType: "Type 2",
    pricePerKwh: 0.28,
    availability: "Available",
    availableChargers: 2,
    totalChargers: 4,
    chargingSpeed: "50 kW",
    address: "456 Green Avenue, Downtown",
  },
  {
    id: 3,
    name: "FastCharge Plus",
    distance: 4.5,
    chargerType: "CCS2",
    pricePerKwh: 0.42,
    availability: "Busy",
    availableChargers: 0,
    totalChargers: 8,
    chargingSpeed: "350 kW",
    address: "789 Highway Road, North Side",
  },
  {
    id: 4,
    name: "GreenVolt Station",
    distance: 5.2,
    chargerType: "CHAdeMO",
    pricePerKwh: 0.32,
    availability: "Available",
    availableChargers: 3,
    totalChargers: 5,
    chargingSpeed: "100 kW",
    address: "321 Park Lane, East District",
  },
  {
    id: 5,
    name: "Urban Charge Point",
    distance: 6.8,
    chargerType: "Type 2",
    pricePerKwh: 0.38,
    availability: "Available",
    availableChargers: 1,
    totalChargers: 3,
    chargingSpeed: "75 kW",
    address: "654 Urban Plaza, West End",
  },
  {
    id: 6,
    name: "MegaWatt Hub",
    distance: 7.4,
    chargerType: "CCS2",
    pricePerKwh: 0.45,
    availability: "Busy",
    availableChargers: 0,
    totalChargers: 10,
    chargingSpeed: "250 kW",
    address: "987 Industrial Way, South Zone",
  },
];

export const getCheapestStation = () => {
  return mockStations.reduce(
    (min, station) => (station.pricePerKwh < min.pricePerKwh ? station : min),
    mockStations[0]
  );
};
